django5/accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns=[
    path('login/',views.login,name='login'),
    path('signup/',views.signup, name='signup'),
    
]

django5/django5/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django6/',include('django6.urls')),
    path('accounts/',include('accounts.urls')),
]

django5/django6/urls.py
from django.urls import path
from .views import Home
from django6.views import *


app_name='django6'

urlpatterns=[
    path('', Home.as_view(), name="django5"),
    
]

django5/accounts/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_id=models.CharField(max_length=32, unique=True, verbose_name="유저 아이디")
    user_pw=models.CharField(max_length=128, verbose_name="유저 비밀번호")
    user_name=models.CharField(max_length=16, unique=True, verbose_name="유저 이름)")
    user_email=models.EmailField(max_length=128, unique=True, verbose_name="유저 이메일")
    user_register_dttm=models.DateTimeField(auto_now_add=True, verbose_name="계정 생성시간")
    
    def __str__(self):
        return self.user_name
    #생성된 객체의 이름을 지정하는 메서드입니다. 이름에서도 알수 있뜻이 str타입을 리턴합니다. 등록해야한다.
    class Meta:
        #db테이블명을 지정해주는 옵션
        db_table="user"
        #테이블명을 지정하는 옵션
        verbose_name="유저"
        #해당테이블의 닉네임
        verbose_name_plural="유저"

django5/django6/models.py
from django.db import models

# Create your models here.

django5/accounts/forms.py
from django import forms
#장고의 forms를 가져옵니다.
from .models import User
#연동시킬 모델인 user모델을 가져옵니다.
from argon2 import PasswordHasher
#비밀번호 암호화에 필요한 클래스를 가져옵니다.

class RegisterForm(forms.ModelForm):
    user_id =forms.CharField(
        label='아이디',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'user-id',
                'placeholder' : '아이디'
            }
        ),
        error_messages={'required':'아이디를 입력해주세요'}
    )

    user_pw =forms.CharField(
        label='비밀번호',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'user-pw',
                'placeholder' : '비밀번호'
            }
        ),
        error_messages={'required':'비밀번호를 입력해주세요'}
    )

    user_pw_confirm =forms.CharField(
        label='비밀번호 확인',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'user-pw-confirm',
                'placeholder' : '비밀번호 확인'
            }
        ),
        error_messages={'required':'비민번호가 일치하지 않습니다'}
    )

    user_name =forms.CharField(
        label='이름',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'user-name',
                'placeholder' : '이름'
            }
        ),
        error_messages={'required':'닉네임을 입력해주세요'}
    )

    user_email =forms.EmailField(
        label='이메일',
        required=True,
        widget=forms.EmailInput(
            attrs={
                'class' : 'user-email',
                'placeholder' : '이메일'
            }
        ),
        error_messages={'required':'이메일을 입력해주세요'}
    )

    
      
    field_order=[
        'user_id',
        'user_pw',
        'user_pw_confirm',
        'user_name',
        'user_email'
    ]
    #추가로 필드 순서를 지정하는 field_order


    class Meta:
        #회원가입폼과 연결시킬 메타데이터들을 입력하는 부분
        model=User
        #유저모델을 연결
        fields=[
            'user_id',
            'user_pw',
            'user_name',
            'user_email'
        ]
        #유저모델중에서 form을 통해 클라이언트로부터 값을 입력받을 필드들만 연결시킵니다.User
    def clean(self):
        cleaned_data=super().clean()
        user_id=cleaned_data.get('user_id','')
        user_pw=cleaned_data.get('user_pw','')
        user_pw_confirm=cleaned_data.get('user_pw_confirm','')
        user_name=cleaned_data.get('user_name','')
        user_email=cleaned_data.get('user_email','')

        if user_pw != user_pw_confirm:
            return self.add_error('user_pw_confirm','비밀번호가 다릅니다')
        elif not(4<=len(user_id)<=16):
            return self.add_error('user_id','아이디는 4~16자로 입력해주세요')
        elif 8> len(user_pw):
            return self.add_error('user_pw','비밀번호는 8자 이상으로 적어주세요')
        else:
            self.user_id=user_id
            self.user_pw=PasswordHasher().hash(user_pw)


class LoginForm(forms.Form):
    user_id =forms.CharField(
        max_length=32,
        label='아이디',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'user-id',
                'placeholder' : '아이디'
            }
        ),
        error_messages={'required':'아이디를 입력해주세요'}
    )

    user_pw =forms.CharField(
        max_length=128,
        label='비밀번호',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'user-pw',
                'placeholder' : '비밀번호'
            }
        ),
        error_messages={'required':'비밀번호를 입력해주세요'}
    )

    field_order=[
        'user_id',
        'user_pw',
    ]

    def clean(self):
        cleaned_data=super().clean()
        user_id=cleaned_data.get('user_id','')
        user_pw=cleaned_data.get('user_pw','')

        if user_id=='':
            return self.add_error('user_id','아이디를 다시 입력해주세요')
        elif user_pw=='':
            return self.add_error('user_pw','비밀번호를 다시 입력해주세요')
        else:
            try:
                user=User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                return self.add_error('user_id','아이디를 존재하지 않습니다')

            try:
                PasswordHasher().verify(user.user_pw, user_pw)
            except exception.VerifyMismatchError:
                return self.add_error('user_pw','비밀번호가 다릅니다')

django5/accounts/views.py
from django.shortcuts import render,redirect
from argon2 import PasswordHasher
from .models import User
from django.db import transaction
from .forms import RegisterForm, LoginForm

def signup(request):
    register_form=RegisterForm()
    #지금까지작성한 RegsiterForm을 가져옵니다
    context={'forms': register_form}
    #아무런 값도 입력하지 않은 빈폼을 register_form이라는 변수에 할당합니다.context변수에 dict타입으로 register_form객체를 넣습니다.
    if request.method =='GET':
        return render(request, '/sign.html' , context)
        #렌더링함수에 context를 전달합니다. 이 과정을 통해 render함수는 accounts/sign.html 파일을 렌더링할때 context에 대한 정보도 같이 전달하게 됩니다
    elif request.method =='POST':
        register_form=RegisterForm(request.POST)
        if register_form.is_valid():
            user=User(
                user_id=register_form.user_id,
                user_pw=register_form.user_pw,
                user_name=register_form.user_name,
                user_email =register_form.user_email
            )
            user.save()
            return redirect('/login.html')
        else:
            context['forms']=register_form
            if register_form.errors:
                for value in register_form.errors.values():
                    context['error']=value

        return render(request, '/sign.html',context)

def login(request):
    loginform = LoginForm()
    context={'forms': loginform}
    if request.method=='GET':
        return render(request, '/login.html',context)

    elif request.method=='POST':
        loginform=LoginForm(request.POST)

        if loginform.is_valid():
            return redirect('/')
        else:
            context['forms']=loginform
            if loginform.errors:
                for value in loginform.errors.values():
                    context['error']=value
        return render(request, '/login.html',context)

django5/django6/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.

class Home(View):
    def get(self,request,*args, **kwargs):
        return render(request,'index.html')

django5/accounts/templates/base.html
<!DOCTYPE html>
<html lang="ko-ki">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" size="16x16">
        <link rel="icon" href="/favicon.ico" type="image/x-icon" size="16x16">
        <title>Bible - {% block title %}{% endblock title %} </title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        
        {% block others %}{% endblock others %}
        
    </head>
    <body>
        {% block content %}
        
        {% endblock content %}
        
    </body>
    </html>

django5/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    로그인
{% endblock title %}
    {% block others %}
    {% endblock others %}
{%block content %}
    {%include 'partials/navbar.html' %}
    <h1>로그인</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {% for form in forms %}
        <div>
            <label for="{{ form.id_for_label}}">{{ form.label }}</label>
            {{ form }}
        </div>
        {% endfor %}
        {if error %}
        {{error}}
        { % endif %}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>

{% endblock content %}

django5/accounts/templates/partials/navbar.html
{% load static %}
<header>
    <h1 class="sitename">사이트명</h1>
    <nav class="three">
      <ul class="list">
        <li><a class="login" href="#">크리스천동아리</a></li>
        <li><a class="login" href="#">기독교기념일</a></li>
        <li><a class="login" href="#">챌린지</a></li>
        <button class="login" href="{% url 'accounts:login' %}">Login</button>
      </ul>
    </nav>
  </header>

django5/accounts/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    회원가입
{% endblock title %}
    {% block others %}
    {% endblock others %}
{%block content %}
    {%include 'partials/navbar.html' %}
    <form action="" method="POST">
            {% csrf_token %}

            {% for form in forms  %}
            <div>
                <label for="{{ form.id_for_label}}">{{ form.label }}</label>
                    {{ form }}
            </div>
            {% endfor %}
            {% if error %}
            {{errors}}
            {% endif %}
            {}
            <input type="submit" value="Sign Up">
    </form>

{% endblock content %}

django5/django6/templates/base.html
<!DOCTYPE html>
<html lang="ko-ki">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" size="16x16">
        <link rel="icon" href="/favicon.ico" type="image/x-icon" size="16x16">
        <title>Bible - {% block title %}{% endblock title %} </title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        
        {% block others %}{% endblock others %}
        
    </head>
    <body>
        {% block content %}
        
        {% endblock content %}
        
    </body>
    </html>

django5/django6/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock title %}
    {% block others %}
    {% endblock others %}
{%block content %}
    {%include 'partials/navbar.html' %}
   
{% endblock content %}

django5/django6/templates/partials/navbar.html
{% load static %}
<header>
    <h1 class="sitename">사이트명</h1>
    <nav class="three">
      <ul class="list">
        <li><a class="login" href="#">크리스천동아리</a></li>
        <li><a class="login" href="#">기독교기념일</a></li>
        <li><a class="login" href="#">챌린지</a></li>
        <button class="login" onclick="location.href='{% url 'accounts:login' %}'">Login</button>
      </ul>
    </nav>
  </header>